
def get_languages():
    return {'am_ET': 'Amharic / አምሃርኛ',
        'ar_001': 'Arabic / الْعَرَبيّة',
        'ar_SY': 'Arabic (Syria) / الْعَرَبيّة',
        'az_AZ': 'Azerbaijani / Azərbaycanca',
        'bg_BG': 'Bulgarian / български език',
        'bn_IN': 'Bengali / বাংলা',
        'bs_BA': 'Bosnian / bosanski jezik',
        'ca_ES': 'Catalan / Català',
        'cs_CZ': 'Czech / Čeština',
        'da_DK': 'Danish / Dansk',
        'de_CH': 'German (CH) / Deutsch (CH)',
        'de_DE': 'German / Deutsch',
        'el_GR': 'Greek / Ελληνικά',
        'en_AU': 'English (AU)',
        'en_CA': 'English (CA)',
        'en_GB': 'English (UK)',
        'en_IN': 'English (IN)',
        'en_US': 'English (US)',
        'es_AR': 'Spanish (AR) / Español (AR)',
        'es_BO': 'Spanish (BO) / Español (BO)',
        'es_CL': 'Spanish (CL) / Español (CL)',
        'es_CO': 'Spanish (CO) / Español (CO)',
        'es_CR': 'Spanish (CR) / Español (CR)',
        'es_DO': 'Spanish (DO) / Español (DO)',
        'es_EC': 'Spanish (EC) / Español (EC)',
        'es_ES': 'Spanish / Español',
        'es_GT': 'Spanish (GT) / Español (GT)',
        'es_MX': 'Spanish (MX) / Español (MX)',
        'es_PA': 'Spanish (PA) / Español (PA)',
        'es_PE': 'Spanish (PE) / Español (PE)',
        'es_PY': 'Spanish (PY) / Español (PY)',
        'es_UY': 'Spanish (UY) / Español (UY)',
        'es_VE': 'Spanish (VE) / Español (VE)',
        'et_EE': 'Estonian / Eesti keel',
        'eu_ES': 'Basque / Euskara',
        'fa_IR': 'Persian / فارسی',
        'fi_FI': 'Finnish / Suomi',
        'fr_BE': 'French (BE) / Français (BE)',
        'fr_CA': 'French (CA) / Français (CA)',
        'fr_CH': 'French (CH) / Français (CH)',
        'fr_FR': 'French / Français',
        'gl_ES': 'Galician / Galego',
        'gu_IN': 'Gujarati / ગુજરાતી',
        'he_IL': 'Hebrew / עִבְרִי',
        'hi_IN': 'Hindi / हिंदी',
        'hr_HR': 'Croatian / hrvatski jezik',
        'hu_HU': 'Hungarian / Magyar',
        'id_ID': 'Indonesian / Bahasa Indonesia',
        'it_IT': 'Italian / Italiano',
        'ja_JP': 'Japanese / 日本語',
        'ka_GE': 'Georgian / ქართული ენა',
        'kab_DZ': 'Kabyle / Taqbaylit',
        'km_KH': 'Khmer / ភាសាខ្មែរ',
        'ko_KP': 'Korean (KP) / 한국어 (KP)',
        'ko_KR': 'Korean (KR) / 한국어 (KR)',
        'lb_LU': 'Luxembourgish',
        'lo_LA': 'Lao / ພາສາລາວ',
        'lt_LT': 'Lithuanian / Lietuvių kalba',
        'lv_LV': 'Latvian / latviešu valoda',
        'mk_MK': 'Macedonian / македонски јазик',
        'ml_IN': 'Malayalam / മലയാളം',
        'mn_MN': 'Mongolian / монгол',
        'ms_MY': 'Malay / Bahasa Melayu',
        'my_MM': 'Burmese / ဗမာစာ',
        'nb_NO': 'Norwegian Bokmål / Norsk bokmål',
        'nl_BE': 'Dutch (BE) / Nederlands (BE)',
        'nl_NL': 'Dutch / Nederlands',
        'pl_PL': 'Polish / Język polski',
        'pt_AO': 'Portuguese (AO) / Português (AO)',
        'pt_BR': 'Portuguese (BR) / Português (BR)',
        'pt_PT': 'Portuguese / Português',
        'ro_RO': 'Romanian / română',
        'ru_RU': 'Russian / русский язык',
        'sk_SK': 'Slovak / Slovenský jazyk',
        'sl_SI': 'Slovenian / slovenščina',
        'sq_AL': 'Albanian / Shqip',
        'sr@latin': 'Serbian (Latin) / srpski',
        'sr_RS': 'Serbian (Cyrillic) / српски',
        'sv_SE': 'Swedish / Svenska',
        'te_IN': 'Telugu / తెలుగు',
        'th_TH': 'Thai / ภาษาไทย',
        'tl_PH': 'Tagalog / Filipino',
        'tr_TR': 'Turkish / Türkçe',
        'uk_UA': 'Ukrainian / українська',
        'vi_VN': 'Vietnamese / Tiếng Việt',
        'zh_CN': 'Chinese (Simplified) / 简体中文',
        'zh_HK': 'Chinese (HK)',
        'zh_TW': 'Chinese (Traditional) / 繁體中文'
    }